--USE CUSTOMERS
--SELECT * FROM CITIES
--SELECT * FROM DISTRICTS
--SELECT * FROM CUSTOMERS

--CREATE DATABASE CUSTOMERS (DATABASE OLUÞTURMA)

--CREATE TABLE CUSTOMERS(           (TABLO OLUÞTURMA)
--ID int identity(1,1) not null primary key,
--CUSTOMERNAME VARCHAR(50),
--TCNUMBER VARCHAR(11),
--GENDER VARCHAR(1),
--EMAIL VARCHAR(50),
--BIRTDATE DATE,
--CITID INT,
--DISTRICTID INT,
--TELNR1 VARCHAR(15),
--TELNR2 VARCHAR(15)
--)

--CREATE TABLE CITIES(
--ID INT IDENTITY(1,1) not null PRIMARY KEY,
--CITY VARCHAR(50)
--)

--CREATE TABLE DISTRICTS(
--ID INT IDENTITY(1,1) not null PRIMARY KEY,
--CITYID INT,
--DISTRICT VARCHAR(50)
--)

--select * from CITIES
--SELECT * FROM DISTRICTS
--SELECT * FROM CUSTOMERS

--CUSTOMERS>TASKS>IMPORT DATA8SANAK MAKÝNE LAZIM) (IMPORT-EXPORT) (EXCCELDEN SQL E VERÝ ÇEKME)

--INSERT INTO CITIES(CITY) VALUES ('ADANA')

--INSERT INTO DISTRICTS(CITYID,DISTRICT) VALUES (37,'ABANA')
--TRUNCATE TABLE CUSTOMERS (TABLO SÝLME)

/*CUSTOMERS tablosundan adý 'A' harfi ile baþlayan kiþileri çeken sorguyu yazýnýz*/
SELECT * FROM CUSTOMERS WHERE CUSTOMERNAME LIKE 'A%'

/*CUSTOMERS tablosunda adý 'A' harfi ile baþlayan erkek müþterileri çeken sorguyu yazýnýz*/
SELECT * FROM CUSTOMERS WHERE CUSTOMERNAME LIKE 'A%' AND GENDER='E'

/*1990 ve 1995 yýllarý arasýnda doðan müþterileri çekiniz.1990 ve 1995  yýllarý dahildir*/
SELECT * FROM CUSTOMERS WHERE BIRTHDATE>='1990-01-01' AND BIRTHDATE<='1995.12.31' 
SELECT * FROM CUSTOMERS WHERE BIRTHDATE BETWEEN '1990-01-01' AND '1995.12.31'
SELECT * FROM CUSTOMERS WHERE YEAR(BIRTHDATE) BETWEEN 1990 AND 1995

/*Ýstanbul'da yaþayan kiþileri Join kullanarak getiren sorguyu yazýnýz*/
SELECT * FROM CUSTOMERS  C 
INNER JOIN CITIES  CT
ON C.CITYID=CT.ID
WHERE CT.CITY='ÝSTANBUL'

/*Ýstanbul'da yaþayan kiþileri subquery kullanarak getiren sorguyu yazýnýz*/
SELECT * FROM CUSTOMERS  C
WHERE C.CITYID *
IN (SELECT ID FROM CITIES WHERE CITY IN ('ÝSTANBUL'))

/*Hangi þehirde kaç müþterimizin olduðu sorguyu yazýnýz*/
SELECT CT.CITY,COUNT(C.ID) AS ToplamMusteri 
FROM CUSTOMERS C 
INNER JOIN CITIES CT
ON C.CITYID=CT.ID
GROUP BY CT.CITY

SELECT *,(SELECT COUNT(*) FROM CUSTOMERS WHERE CITYID=CT.ID) AS ToplamMusteri
FROM CITIES CT

/*10'dan fazla müþterimiz olan þehirleri müþteri sayýsý ile birlikte müþteri
sayýsýna göre fazladan aza doðru sýralý þekilde getiriniz*/
SELECT CT.CITY,COUNT(C.ID) AS ToplamMusteri 
FROM CUSTOMERS C 
INNER JOIN CITIES CT
ON C.CITYID=CT.ID
GROUP BY CT.CITY
HAVING COUNT(C.ID)>10
ORDER BY COUNT(C.ID) DESC

SELECT CITY,(SELECT COUNT(*) FROM CUSTOMERS WHERE CITYID=CT.ID) 
FROM CITIES CT
WHERE (SELECT COUNT(*) FROM CUSTOMERS WHERE CITYID=CT.ID)>10

/*Hangi þehirde kaç erkek,kaç kadýn müþterimizin olduðu bilgisini þekildeki gibi getiren sorguyu yazýnýz*/
SELECT CT.CITY,C.GENDER,COUNT(C.ID) AS ToplamMusteri 
FROM CUSTOMERS C 
INNER JOIN CITIES CT
ON C.CITYID=CT.ID
GROUP BY CT.CITY,C.GENDER
ORDER BY CT.CITY,C.GENDER


/*Hangi þehirde kaç erkek,kaç kadýn müþterimizin olduðu bilgisini getiren sorguyu yazýnýz*/
SELECT CITY AS SEHIRADI,
(SELECT COUNT(*) FROM CUSTOMERS WHERE CITYID=CT.ID AND GENDER='E') AS ERKEKSAYISI,
(SELECT COUNT(*) FROM CUSTOMERS WHERE CITYID=CT.ID AND GENDER='K') AS KADINSAYISI
FROM CITIES CT

/*CUSTOMERS tablosuna yaþ grubu için yenibir alan ekleyeniz.Bu iþlemi hem management studio ile hem de sql kodu ile yapýnýz.
Alanýn adý AGEGROUP veritipi varchar(50)*/
ALTER TABLE CUSTOMERS ADD AGEGROUP VARCHAR(50)
SELECT * FROM CUSTOMERS

/*CUSTOMERS tablosuna eklediðiniz AGEGROUP alanýný 20-35 yaþ arasý,36-45 yaþ arasý,46-55 yaþ arasý,55-65 yaþ arasý ve 
65 yaþ üstü olarak güncelleyiniz.*/
SELECT * FROM CUSTOMERS

UPDATE CUSTOMERS SET AGEGROUP ='20-35 YAÞ'
WHERE DATEDIFF(YEAR,BIRTHDATE,GETDATE()) BETWEEN 20 AND 35

UPDATE CUSTOMERS SET AGEGROUP ='36-45 YAÞ'
WHERE DATEDIFF(YEAR,BIRTHDATE,GETDATE()) BETWEEN 36 AND 45

UPDATE CUSTOMERS SET AGEGROUP ='46-55 YAÞ'
WHERE DATEDIFF(YEAR,BIRTHDATE,GETDATE()) BETWEEN 46 AND 55

UPDATE CUSTOMERS SET AGEGROUP ='55-65 YAÞ'
WHERE DATEDIFF(YEAR,BIRTHDATE,GETDATE()) BETWEEN 55 AND 65

UPDATE CUSTOMERS SET AGEGROUP ='65 YAÞ ÜSTÜ'
WHERE DATEDIFF(YEAR,BIRTHDATE,GETDATE()) > 65

/*CUSTOMERS tablosunda müþterinin yaþýna göre hesaplayarak þekildeki gibi bir sonuç getiriniz.
AGEGROUP alaný kullanýlmadan sorgu getirilecektir.*/
SELECT 
CASE
 WHEN DATEDIFF(YEAR,BIRTHDATE,GETDATE()) BETWEEN 20 AND 35 THEN '20-35 YAÞ ARASI'
 WHEN DATEDIFF(YEAR,BIRTHDATE,GETDATE()) BETWEEN 36 AND 45 THEN '36-45 YAÞ ARASI'
 WHEN DATEDIFF(YEAR,BIRTHDATE,GETDATE()) BETWEEN 46 AND 55 THEN '46-55 YAÞ ARASI'
 WHEN DATEDIFF(YEAR,BIRTHDATE,GETDATE()) BETWEEN 55 AND 65 THEN '55-65 YAÞ ARASI'
 WHEN DATEDIFF(YEAR,BIRTHDATE,GETDATE()) >65 THEN '65 YAÞ ÜSTÜ'
 END AGEGROUP
 COUNT(*) CUSTOMERCOUNT
 FROM CUSTOMERS
 GROUP BY
 CASE
 WHEN DATEDIFF(YEAR,BIRTHDATE,GETDATE()) BETWEEN 20 AND 35 THEN '20-35 YAÞ ARASI'
 WHEN DATEDIFF(YEAR,BIRTHDATE,GETDATE()) BETWEEN 36 AND 45 THEN '36-45 YAÞ ARASI'
 WHEN DATEDIFF(YEAR,BIRTHDATE,GETDATE()) BETWEEN 46 AND 55 THEN '46-55 YAÞ ARASI'
 WHEN DATEDIFF(YEAR,BIRTHDATE,GETDATE()) BETWEEN 55 AND 65 THEN '55-65 YAÞ ARASI'
 WHEN DATEDIFF(YEAR,BIRTHDATE,GETDATE()) >65 THEN '65 YAÞ ÜSTÜ'
END
ORDER BY AGEGROUP

/*2.YOL*/
SELECT AGEGROUP2,COUNT(TMP.ID) AS CUSTOMERCOUNT FROM
(
SELECT *,
CASE
 WHEN DATEDIFF(YEAR,BIRTHDATE,GETDATE()) BETWEEN 20 AND 35 THEN '20-35 YAÞ ARASI'
 WHEN DATEDIFF(YEAR,BIRTHDATE,GETDATE()) BETWEEN 36 AND 45 THEN '36-45 YAÞ ARASI'
 WHEN DATEDIFF(YEAR,BIRTHDATE,GETDATE()) BETWEEN 46 AND 55 THEN '46-55 YAÞ ARASI'
 WHEN DATEDIFF(YEAR,BIRTHDATE,GETDATE()) BETWEEN 55 AND 65 THEN '55-65 YAÞ ARASI'
 WHEN DATEDIFF(YEAR,BIRTHDATE,GETDATE()) >65 THEN '65 YAÞ ÜSTÜ'
END AGEGROUP2
FROM CUSTOMERS
) TMP
GROUP BY AGEGROUP2
ORDER BY AGEGROUP2

/*Ýstanbul'da yaþayýp ilçesi 'Kadýköy' dýþýnda olanlarý listeyiniz.*/
SELECT * FROM CUSTOMERS C
INNER JOIN CITIES CT
ON C.CITYID=CT.ID
INNER JOIN DISTRICTS D
ON C.DISTRICTID=D.ID
WHERE CT.CITY='ÝSTANBUL' AND D.DISTRICT ='KADIKÖY'

SELECT * FROM CUSTOMERS
WHERE CITYID IN (SELECT ID FROM CITIES WHERE CITY = 'ÝSTANBUL')
AND DISTRICTID IN (SELECT ID FROM DISTRICTS WHERE DISTRICT = 'KADIKÖY')
 
/*Müþterilerimizin telefon numaralarýnýn operatör bilgisini getirmek istiyoruz.TELNR1 ve TELNR2
alanlarýnýn yanýna operatör numarasýný (532),(505) gibi getirmek istiyoruz.Bu sorgu için gereken SQL cümlesini yazýnýz*/
SELECT *,
SUBSTRING(TELNR1,1,5)AS OPERATÖR1,
SUBSTRING(TELNR2,1,5)AS OPERATÖR2
FROM CUSTOMERS

SELECT SUBSTRING('(542)5255514',1,5)
SELECT LEFT('(542)5255514',5)

/*Her ilde en çok müþteriye sahip olduðumuz ilçeleri müþteri saysýsýna göre çoktan aza doðru
sýralý þekildE getirmek için gerekn sorguyu yazýnýz*/
SELECT CT.CITY,D.DISTRICT,COUNT(C.ID) AS CUSTOMERCOUNT
FROM CUSTOMERS C
INNER JOIN CITIES CT
ON C.CITYID=CT.ID
INNER JOIN DISTRICTS D
ON C.DISTRICTID=D.ID
GROUP BY CT.CITY,D.DISTRICT
ORDER BY CT.CITY,COUNT(C.ID) DESC

/*Müþterilerin doðum günlerini haftanýn günü olarak getiren sorguyu yazýnýz*/
SET LANGUAGE Turkish
SELECT 
CUSTOMERNAME,DATENAME(DW,BIRTHDATE) BIRTHDAY
 FROM CUSTOMERS

 /*Doðum günü bugün olan müþterilerin listesini getiriniz*/
 SELECT * FROM CUSTOMERS
 WHERE MONTH(BIRTHDATE) = MONTH(GETDATE())
 AND
 DATEPART(DAY,BIRTHDATE) = DATEPART(DAY,GETDATE())